// input
export const inputActions = {
  MOUSE_DOWN: 'MOUSE_DOWN',
  MOUSE_UP: 'MOUSE_UP',
  KEY_DOWN: 'KEY_DOWN',
  KEY_UP: 'KEY_UP',
  INPUT_EVENT: 'INPUT_EVENT',
  KEY_PRESS_START: 'KEY_PRESS_START',
  KEY_PRESS_INC: 'KEY_PRESS_INC',
  KEY_PRESS_END: 'KEY_PRESS_END'
};

// movement
export const movementActions = {
  SET_ROTATION: 'SET_ROTATION',
  SET_HOTZONE: 'SET_HOTZONE',
  CLEAR_HOTZONE: 'CLEAR_HOTZONE',
  SET_TURNING: 'SET_TURNING',
  CLEAR_TURNING: 'CLEAR_TURNING',
  SET_UNLOCKABLE: 'SET_UNLOCKABLE',
  CLEAR_UNLOCKABLE: 'CLEAR_UNLOCKABLE'
};

// pick
export const pickActions = {
  REDUCE_PICK_LIFE: 'REDUCE_PICK_LIFE',
  REDUCE_PICKLIVES: 'REDUCE_PICKLIVES',
  CLEAR_GAME: 'CLEAR_GAME'
};

// game
export const gameActions = {
  TOGGLE_UNLOCK: 'TOGGLE_UNLOCK',
  TOGGLE_GAME_OVER: 'TOGGLE_GAME_OVER',
  TOGGLE_NOTIFICATION: 'TOGGLE_NOTIFICATION',
  SET_REDIRECT: 'SET_REDIRECT',
  SETTINGS: 'SETTINGS'
};

// user
export const userActions = {
  SET_AUTH: 'SET_AUTH',
  SET_NAVIGATION: 'SET_NAVIGATION',
  LOGOUT: 'LOGOUT'
};
